import { StyleSheet, Dimensions } from 'react-native';

export default StyleSheet.create({
    hosgeldiniz: {
        flex: 1,
        justifyContent: 'center',
        backgroundColor: 'white',
    },
    baslik: {
        marginLeft: 10,
        fontSize: 40,
        fontWeight: 'bold',
        color: '#BE9FE1',
    },
    hosgeldinizResim: {
        width: 392,
        height: 321,
        resizeMode: "contain",
    },
    altButonView: {
        marginTop: 50,
        flexDirection: 'row',
        justifyContent: 'space-evenly',
    },
    altButon: {
        backgroundColor: '#BE9FE1',
        width: 150,
        height: 50,
        padding: 12,
        alignItems: 'center',
        marginTop: 10,
        marginBottom: 10,
        borderRadius: 10,
    },
    kayitGirisParola: {
        display: 'flex',
        flex: 1,
        justifyContent: 'center',
        backgroundColor: 'white',
        alignItems: 'center',
    },
    kayitGirisResim: {
        width: 250,
        height: 250,
        alignContent: 'center',
    },
    parolaResim: {
        height: 200,
        width: 250,
        alignContent: 'center',
    },
    form: {
        backgroundColor: 'white',
        borderColor: '#F1F1F6',
        borderWidth: 1,
        borderRadius: 10,
        marginBottom: 10,
    },
    input: {
        height: 60,
        width: 300,
        borderWidth: 1,
        borderBottomColor: '#F1F1F6',
        padding: 10,
        borderTopWidth: 0,
        borderRightWidth: 0,
        borderLeftWidth: 0,
        fontSize: 17,
    },
    inputSon: {
        height: 60,
        width: 300,
        padding: 10,
        fontSize: 17,
    },
    inputParola: {
        height: 60,
        width: 300,
        padding: 10,
        fontSize: 17,
    },
    buton: {
        backgroundColor: '#BE9FE1',
        height: 50,
        padding: 12,
        alignItems: 'center',
        marginTop: 10,
        marginBottom: 10,
        borderRadius: 10,
    },
    butonIsim: {
        color: 'white',
        fontSize: 17,
    },
    parolaLink: {
        alignItems: 'flex-end',
        textAlign: 'right',
        color: '#E1CCEC',
        marginTop: 4,
        marginBottom: 7,
        fontSize: 13,
    },
    link: {
        color: '#E1CCEC',
        fontSize: 13,
    },
});